package Exception;

public class Exception2 {

	public static void main(String[] args) {
	 
		try {
		int data = 50/0;
		
		}catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println(e);
		}
		System.out.println("Re of the code");

	}

}
